import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StagewiseToolbar } from "@stagewise/toolbar-next";
import Header from "./components/AppHeader";
import Sidebar from "./components/AppSidebar";
import MobileSidebar from "./components/AppMobileSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const stagewiseConfig = {
  plugins: [],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Sidebar />
        <MobileSidebar />
        {children}
      </body>
      {process.env.NODE_ENV === "development" && (
        <StagewiseToolbar config={stagewiseConfig} />
      )}
    </html>
  );
}
